repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v1.6.0'  # Use the sha / tag you want to point at
    hooks:
    -   id: autopep8
-   repo: https://github.com/pycqa/flake8
    rev: '4.0.1'  # pick a git hash / tag to point to
    hooks:
    -   id: flake8
    additional_dependencies: [flake8-docstrings]
